# Generated by Django 6.0.4 on 2026-04-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={},
        ),
    ]
