# Generated by Django 6.0.4 on 2026-04-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projectimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Изображение проекта', 'verbose_name_plural': 'Изображения проектов'},
        ),
    ]
