# Generated by Django 6.0.4 on 2026-04-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plantcategory_plant_plantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterModelOptions(
            name='plantcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория растения', 'verbose_name_plural': 'Категории растений'},
        ),
        migrations.AlterModelOptions(
            name='plantimage',
            options={'verbose_name': 'Изображение растения', 'verbose_name_plural': 'Изображения растений'},
        ),
        migrations.AddField(
            model_name='plant',
            name='age',
            field=models.CharField(blank=True, max_length=100, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать в избранных'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pot_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер горшка'),
        ),
        migrations.AddField(
            model_name='plant',
            name='price_text',
            field=models.CharField(blank=True, help_text='Если заполнено, будет показано вместо price_from. Например: по запросу', max_length=100, verbose_name='Текст цены'),
        ),
        migrations.AddField(
            model_name='plant',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='count_label',
            field=models.CharField(blank=True, help_text='Например: 150+ видов', max_length=50, verbose_name='Надпись количества'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plantcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='main.plantcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.CharField(blank=True, max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='latin_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Латинское название'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='plants/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.plant', verbose_name='Растение'),
        ),
        migrations.CreateModel(
            name='PlantSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(blank=True, verbose_name='Слаг')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.plantcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория растения',
                'verbose_name_plural': 'Подкатегории растений',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='main.plantsubcategory', verbose_name='Подкатегория'),
        ),
    ]
