# Generated by Django 6.0.4 on 2026-04-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_plant_options_alter_plantcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterModelOptions(
            name='plantsubcategory',
            options={'ordering': ['name'], 'verbose_name': 'Подкатегория растения', 'verbose_name_plural': 'Подкатегории растений'},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pot_size',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='plantsubcategory',
            name='sort_order',
        ),
    ]
